version: '3.1'

services:
    db:
        image: mysql:8.0
        container_name: libs_mysql
        environment:
        - MYSQL_USER=Andrey
        - MYSQL_PASSWORD=123
        - MYSQL_ROOT_PASSWORD=root
        ports:
        - 3306:3306
        volumes:
        - ./mysql:/var/lib/mysql/